// The following opcodes are used in this design. 
// You can try to build a testbench to test this ALU desugn.
// 10'b1001101000  subr
// 10'b0110010010  addc
// 10'b0010101000  incb
// 10'b0100101000  inca
// 10'b0110000010  add
// 10'b0110000000  xor
// 10'b0010001000  movb
// 10'b0001001000  xnor
// 10'b0111001000  minus1
// 10'b0100000000  abn
// 10'b1000000010  sllb
// 10'b0100001000  mova
// 10'b0000000011  slla
// 10'b0000000000  Zeros




module lut_alu (
    input  logic        clk,
    input  logic        reset,
    input  logic [9:0]  opcode,
    input  logic [7:0]  A,
    input  logic [7:0]  B,
    input  logic        CI,
    //input  logic        PI,
    output logic [7:0]  Z,
    output logic        CO,
    //output logic        PO
);

    // Internal signal declarations (adjusted for 8-bit)
    logic [7:0] P, G, Ci;
    reg [7:0]   z_d;
    //reg         po_d;
    reg         co_d;
    logic [7:0] pp, gg;

    // Propagate function design (8-bit)
    function automatic logic [7:0] Pf(
        input logic [9:0] opcd,
        input logic [7:0] A_in,
        input logic [7:0] B_in
    );
        logic [7:0] p;
        for(int ix=0; ix<8; ix+=1) begin
            p[ix] = (~A_in[ix]) & (~B_in[ix]) & opcd[5] |
                    (~A_in[ix]) & ( B_in[ix]) & opcd[2] |
                    ( A_in[ix]) & (~B_in[ix]) & opcd[1] |
                    ( A_in[ix]) & ( B_in[ix]) & opcd[0];
        end
        return p;
    endfunction : Pf

    // Generate function design (8-bit)
    function automatic logic [7:0] Gf(
        input logic [9:0] opcd,
        input logic [7:0] A_in,
        input logic [7:0] B_in
    );
        logic [7:0] g;
        for(int ix=0; ix<8; ix+=1) begin
            g[ix] = (~A_in[ix]) & (~B_in[ix]) & opcd[9] |
                    (~A_in[ix]) & ( B_in[ix]) & opcd[8] |
                    ( A_in[ix]) & (~B_in[ix]) & opcd[3] |
                    ( A_in[ix]) & ( B_in[ix]) & opcd[4];
        end
        return g;
    endfunction : Gf

    // Combinational logic section
    always_comb begin
        // Call functions to calculate P and G
        pp = Pf(opcode, A, B);
        gg = Gf(opcode, A, B);

        // Carry-in selection for the 0-th bit for differnet types of operation
        case({opcode[7], opcode[6]})
            2'b00   : Ci[0] = 1'b0; // for bit wise logic operation (and, or, xor....)
            2'b01   : Ci[0] = 1'b1;
            2'b10, 
            2'b11   : Ci[0] = CI;
            default : Ci[0] = 1'bX;
        endcase

        // Ripple carry chain calculation
        for(int ix=1; ix<8; ix+=1) begin
            Ci[ix] = gg[ix-1] | (pp[ix-1] & Ci[ix-1]);
        end

        // Calculate final carry-out and intermediate results
        // co_d is the carry generated by the most significant bit
        co_d = gg[7] | (pp[7] & Ci[7]); 
        
        z_d  = pp ^ Ci;
        //po_d = PI;
    end

    // Sequential logic section (with asynchronous reset)
    always_ff @(posedge clk or posedge reset) begin
        if(reset) begin
            Z  <= 8'h00;
            CO <= 1'b0;
            //PO <= 1'b0;
        end else begin
            Z  <= #1 z_d;
            CO <= #1 co_d;
            //PO <= #1 po_d;
        end
    end

endmodule : lut_alu
